// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace CGUISoundTags
{
	// 버튼
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ButtonClick);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ButtonMainAction);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ButtonHover);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ButtonPositive);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ButtonNegative);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ButtonDisabled);

	// 모달 / 바텀시트
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ModalOpen);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ModalClose);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BottomSheetOpen);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BottomSheetClose);

	// 알림
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NotificationInfo);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NotificationSuccess);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NotificationError);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NotificationWarning);

	// 탭 / 토글
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TabSwitch);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ToggleOn);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ToggleOff);

	// 보상
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RewardCoin);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RewardDiamond);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RewardBrick);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BrickPop);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RewardCompanyLevelUp);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RewardGeneric);

	// 재화 칩 — 자릿수 승격(만/억/조/경)
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ResourceDigitMilestone);

	// 업그레이드/강화 (빌딩, 공장, 오피스 확장, 직원 등 모든 UpgradeSlot 공통)
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UpgradeSuccess);

	// 구매
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PurchaseSuccess);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PurchaseFail);

	// 가챠
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GachaPull);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GachaResultRare);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GachaResultEpic);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GachaResultLegendary);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GachaBuildup);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GachaFlash);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GachaCardPop);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GachaShine);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GachaStamp);

	// 잠재 재설정 — 가챠와 분리한다(GachaPull 은 4초 스핀휠이라 1회성 리롤엔 과하다)
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PotentialReroll);

	// 농땡이 직원 캐치 링 탭
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Catch);

	// 그룹 매칭용 (parent tag)
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GroupAll);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GroupNotification);
	COMPANYGROWTHRENEWAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GroupGacha);
}
